name: Build & Deploy to Railway

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MinimalApiDemoAOT/MinimalApiDemoAOT.csproj

      - name: Build
        run: dotnet build MinimalApiDemoAOT/MinimalApiDemoAOT.csproj --no-restore --configuration Release

  deploy-to-railway:
    needs: build-and-test
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: |
          cd MinimalApiDemoAOT
          railway up --service=${{ env.SERVICE_ID }}
