name: Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: direstrepobr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./MinimalApiDemoAOT
          file: ./MinimalApiDemoAOT/Dockerfile
          push: true
          tags: direstrepobr/minimal-api-demo:aot
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login
        
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd MinimalApiDemoAOT
          railway link --service ${{ secrets.RAILWAY_SERVICE }}
          railway up
