name: Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: direstrepobr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./MinimalApiDemoAOT
          file: ./MinimalApiDemoAOT/Dockerfile
          push: true
          tags: direstrepobr/minimal-api-demo:aot
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy to Railway
        run: |
          cd MinimalApiDemoAOT
          RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }} railway link --project c17144a1-ab5c-4b42-b368-a17c90ea8a9e --environment 81ef578a-6dfd-41ec-a77e-ceb350527cd3 --service a51bbd9c-6389-4342-8342-0de4cb6ded3b
          RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }} railway up
